services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind : 
            $karserRecaptcha3Enabled: '%karser_recaptcha3.enabled%'

    MonsieurBiz\SyliusAntiSpamPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    monsieurbiz.anti_spam.validators.registry: '@MonsieurBiz\SyliusAntiSpamPlugin\Registry\ValidatorsRegistry' 

    MonsieurBiz\SyliusAntiSpamPlugin\Email\Sender:
        decorates: 'sylius.email_sender'
        arguments: ['@MonsieurBiz\SyliusAntiSpamPlugin\Email\Sender.inner']

    MonsieurBiz\SyliusAntiSpamPlugin\EventListener\QuarantineItemAwareListener:
        tags:
            - name: 'doctrine.event_listener'
              event: 'prePersist'
    
    MonsieurBiz\SyliusAntiSpamPlugin\EventListener\QuarantineInitializeUpdateListener:
        tags:
            - { name: kernel.event_listener, event: monsieurbiz_anti_spam.quarantine_item.initialize_update }
